# Generated by Django 5.2.6 on 2025-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variaton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variaton',
            new_name='variations',
        ),
    ]
